<a href="https://colab.research.google.com/github/Hassan-jr/Deep-Learning/blob/main/00_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch. __version__


'1.13.1+cu116'

# Scaler

In [2]:
scaler = torch.tensor(7)
scaler, scaler.dtype, scaler.item(),scaler.ndim



(tensor(7), torch.int64, 7, 0)

# Vector

In [3]:
vector = torch.tensor([10,10])
vector.size()
vector.dtype, vector.shape



(torch.int64, torch.Size([2]))

In [4]:
vector.ndim

1

# MATRIX

In [5]:
 A = torch.tensor([[4,5,6,7],
                   [9,5,4,2]])
 A.ndim, A.shape

(2, torch.Size([2, 4]))

In [6]:
X= A[0,2]
X

tensor(6)

In [7]:
TENSOR = torch.tensor([[[1,2,3,4]],
                       [[5,6,7,8,]],
                       [[10,11,12,13]]])
TENSOR.shape

torch.Size([3, 1, 4])

In [8]:
A = TENSOR[:,:,3]
A
TENSOR.ndim

3

In [9]:
B = torch.rand(size=(3,3,3))
B

tensor([[[0.1428, 0.9167, 0.5896],
         [0.2341, 0.5873, 0.2534],
         [0.2218, 0.8750, 0.2673]],

        [[0.8787, 0.9915, 0.1815],
         [0.4906, 0.3248, 0.2214],
         [0.4042, 0.2391, 0.2447]],

        [[0.6887, 0.0637, 0.9747],
         [0.0995, 0.8360, 0.7304],
         [0.8642, 0.4284, 0.9160]]])

# Matrix Multiplication

In [10]:
C = torch.rand(size=(3,2))
D = torch.rand(size=(2,3))
E = torch.mm(C,D)
print(f"C is : {C}")
print(f"\n D is : {D}")
print(f"\n C * D is : {E}")

C is : tensor([[0.6126, 0.1505],
        [0.4040, 0.8134],
        [0.4521, 0.3016]])

 D is : tensor([[0.4604, 0.0337, 0.7534],
        [0.0832, 0.4258, 0.7890]])

 C * D is : tensor([[0.2945, 0.0848, 0.5803],
        [0.2537, 0.3600, 0.9462],
        [0.2332, 0.1437, 0.5786]])


In [11]:
#range
range = torch.arange(1,10,1)
range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
C.dtype, D.dtype, E.dtype

(torch.float32, torch.float32, torch.float32)

In [13]:
#ZEROS AND ONES
one = torch.ones(size=(3,3))
zeros = torch.zeros(size=(4,4))
one, zeros

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]), tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [14]:
#Tensor addito
TENSOR + 10

tensor([[[11, 12, 13, 14]],

        [[15, 16, 17, 18]],

        [[20, 21, 22, 23]]])

In [15]:
TENSOR + TENSOR

tensor([[[ 2,  4,  6,  8]],

        [[10, 12, 14, 16]],

        [[20, 22, 24, 26]]])

In [16]:
# SUBTRACTION
TENSOR - 5

tensor([[[-4, -3, -2, -1]],

        [[ 0,  1,  2,  3]],

        [[ 5,  6,  7,  8]]])

In [17]:
TENSOR - TENSOR

tensor([[[0, 0, 0, 0]],

        [[0, 0, 0, 0]],

        [[0, 0, 0, 0]]])

In [18]:
#MULTIPLICATON
TENSOR * 10

tensor([[[ 10,  20,  30,  40]],

        [[ 50,  60,  70,  80]],

        [[100, 110, 120, 130]]])

In [19]:
#Transpose
print(f"ORIGINAL TENSOR:\n {TENSOR}")
print(f"Tranposed TENOSR:\n {TENSOR.T}")

ORIGINAL TENSOR:
 tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[10, 11, 12, 13]]])
Tranposed TENOSR:
 tensor([[[ 1,  5, 10]],

        [[ 2,  6, 11]],

        [[ 3,  7, 12]],

        [[ 4,  8, 13]]])


<ipython-input-19-a1258bb001c3>:3: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  print(f"Tranposed TENOSR:\n {TENSOR.T}")


In [20]:
#min
TENSOR.min()
torch.min(TENSOR)

tensor(1)

In [21]:
#mean
torch.mean(TENSOR,dtype= torch.float32)
TENSOR.type(torch.float32).mean()

tensor(6.8333)

In [22]:
#max
TENSOR.max(), TENSOR.argmax()

(tensor(13), tensor(11))

In [23]:
TENSOR



tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[10, 11, 12, 13]]])

In [24]:
TENSOR.dtype

torch.int64

In [25]:
### ERROR TO BE SOLVED LATER
T = TENSOR.type(torch.int32)
T.dtype

torch.int32

In [26]:
!nvidia-smi


Wed Feb  8 07:10:31 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0    29W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [27]:
import torch
torch.cuda.is_available()

True

# putting tensors and models on the gpu

In [28]:
device = 'cuda' if torch.cuda.is_available () else "cpu"
device

'cuda'

In [29]:

tensor = torch.tensor([1,2,5])
print (tensor, tensor.device)

tensor([1, 2, 5]) cpu


In [30]:
#move from cpu to cuda
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 5], device='cuda:0')

## moving tensor back to gpu

In [33]:
#if tensor is on gpu cant transform it to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [34]:
# to fix the above error
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 5])

# Reshaping, stacking, squeezing and unsqueezing

In [36]:
# Reshaping
Reshape = torch.tensor([[1,2,3,4],
                        [5,6,7,8],
                        [10,11,12,13]])
Reshape.size(), Reshape.shape, Reshape

(torch.Size([3, 4]), torch.Size([3, 4]), tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [10, 11, 12, 13]]))

In [39]:
# Reshape now
Reshaped = torch.reshape(Reshape, [6,2])
Reshaped

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [10, 11],
        [12, 13]])

In [50]:
# Stacking
x2 = torch.tensor([1,2,3,4])
stacked = torch.stack([x2,x2,x2,x2],dim=0)
stacked

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

In [53]:
#unsqueeze adds one dim
unsqueezed = Reshape.unsqueeze(dim=1)
unsqueezed

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[10, 11, 12, 13]]])

In [55]:
squeezed = unsqueezed.squeeze()
squeezed

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]])